export const REASON_CODES = {
  actionFocusFailed: "ACTION_FOCUS_FAILED",
  actionScrollFailed: "ACTION_SCROLL_FAILED",
  actionTapFailed: "ACTION_TAP_FAILED",
  actionTypeFailed: "ACTION_TYPE_FAILED",
  ok: "OK",
  adapterError: "ADAPTER_ERROR",
  ambiguousMatch: "AMBIGUOUS_MATCH",
  configurationError: "CONFIGURATION_ERROR",
  deviceUnavailable: "DEVICE_UNAVAILABLE",
  flowFailed: "FLOW_FAILED",
  interruptionUnclassified: "INTERRUPTION_UNCLASSIFIED",
  interruptionResolutionFailed: "INTERRUPTION_RESOLUTION_FAILED",
  interruptionRecoveryStateDrift: "INTERRUPTION_RECOVERY_STATE_DRIFT",
  missingBounds: "MISSING_BOUNDS",
  noMatch: "NO_MATCH",
  ocrAmbiguousTarget: "OCR_AMBIGUOUS_TARGET",
  ocrLowConfidence: "OCR_LOW_CONFIDENCE",
  ocrNoMatch: "OCR_NO_MATCH",
  ocrPostVerifyFailed: "OCR_POST_VERIFY_FAILED",
  ocrProviderError: "OCR_PROVIDER_ERROR",
  policyDenied: "POLICY_DENIED",
  retryExhaustedNoStateChange: "RETRY_EXHAUSTED_NO_STATE_CHANGE",
  replayRefusedHighRiskBoundary: "REPLAY_REFUSED_HIGH_RISK_BOUNDARY",
  replayRecommended: "REPLAY_RECOMMENDED",
  resumeRefusedStateDrift: "RESUME_REFUSED_STATE_DRIFT",
  checkpointUnavailable: "CHECKPOINT_UNAVAILABLE",
  networkWaitRetryable: "NETWORK_WAIT_RETRYABLE",
  networkWaitRetryExhausted: "NETWORK_WAIT_RETRY_EXHAUSTED",
  networkBackendTerminal: "NETWORK_BACKEND_TERMINAL",
  networkOfflineTerminal: "NETWORK_OFFLINE_TERMINAL",
  networkAmbiguityUnresolved: "NETWORK_AMBIGUITY_UNRESOLVED",
  timeout: "TIMEOUT",
  unsupportedOperation: "UNSUPPORTED_OPERATION",
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
